import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, getSession, useSession } from "next-auth/react";
import { useState } from "react";
import { api } from "../utils/api";
import bcrypt from 'bcryptjs'

const Home: NextPage = () => {
  const {data: passwordData} = api.admin.getPassword.useQuery();
  const {data: purchaseOrderData} = api.purchaseOrder.getPurchaseOrderDetails.useQuery({purchaseOrderId: '1'});
  console.log(purchaseOrderData)
  

  return (
    <>
      <Head>
        <title>Book Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Bletsch <span className="text-[hsl(280,100%,70%)]">Book</span> Boys
          </h1>
          <div className="flex flex-col items-center gap-2">
              {<TestPurchase/>}
              {passwordData ? <AuthShowcase/> : <CreateAdmin/>}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const sessionData = useSession();
  console.log(sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData.status==='authenticated' ? () => void signOut() : () => void signIn("credentials",{ callbackUrl: 'http://localhost:3000/dashboard' })}
      >
        {sessionData.status==='authenticated' ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

const CreateAdmin: React.FC = () => {
  const SALT_ROUNDS = 10;
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const adminPass = api.admin.createAdminPassword.useMutation();



  function handlePasswordSubmit(pass: string, confirmPass: string){
      console.log(pass)
      const salt = bcrypt.genSaltSync(SALT_ROUNDS);
      const hash = bcrypt.hashSync(pass, salt);
      if (pass === confirmPass){
        adminPass.mutate({
          password: hash
        });
      }
  }
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-white">Please create an Admin Password</p>
      <label id="password" className="text-white">Enter Password:</label>
      <input type="text" id="first" name="first" onChange={e => {setNewPassword(e.currentTarget.value)}}/>
      <label id="confirm" className="text-white">Re-Type Password:</label>
      <input type="text" id="confirm" name="confirm" onChange={e => {setConfirmPassword(e.currentTarget.value)}}/>
      <button type="submit" className="text-white" onClick={e => handlePasswordSubmit(newPassword, confirmPassword)}>Submit</button>
    </div>
  );
};


const TestPurchase: React.FC = () => {
  const [isbn, setISBN] = useState('');
  const [orderId, setOrderId] = useState('');
  const [id, setId] = useState('');
  const [quantity, setQuantity] = useState('');
  const [price, setPrice] = useState('');
  const purchase = api.purchaseOrder.deletePurchaseOrder.useMutation();



  function handlePasswordSubmit(isbn: string, quantity: string, orderId: string, price: string, id: string){
      purchase.mutate({
        purchaseOrderId: orderId,
      })
  }

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <label id="password" className="text-white">Order ID:</label>
      <input type="text" id="first" name="first" onChange={e => {setOrderId(e.currentTarget.value)}}/>
      <label id="password" className="text-white">ID:</label>
      <input type="text" id="first" name="first" onChange={e => {setId(e.currentTarget.value)}}/>
      <label id="password" className="text-white">ISBN:</label>
      <input type="text" id="first" name="first" onChange={e => {setISBN(e.currentTarget.value)}}/>
      <label id="confirm" className="text-white">Price:</label>
      <input type='text' id="confirm" name="confirm" onChange={e => {setPrice(e.currentTarget.value)}}/>
      <label id="confirm" className="text-white">Quantity:</label>
      <input type="text" id="confirm" name="confirm" onChange={e => {setQuantity(e.currentTarget.value)}}/>
      <button type="submit" className="text-white" onClick={e => handlePasswordSubmit(isbn, quantity, orderId, price, id)}>Submit</button>
    </div>
  );
};
